"""Initial schema

Revision ID: ab369e851163
Revises:
Create Date: 2026-09-04 03:28:25.354518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab369e851163'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('entity_type', sa.String(length=100), nullable=False),
                    sa.Column('entity_id', sa.Integer(), nullable=False),
                    sa.Column('action', sa.String(length=100), nullable=False),
                    sa.Column('before_snapshot', sa.JSON(), nullable=True),
                    sa.Column('after_snapshot', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_audit_logs_entity_id'),
        'audit_logs',
        ['entity_id'],
        unique=False)
    op.create_index(
        op.f('ix_audit_logs_entity_type'),
        'audit_logs',
        ['entity_type'],
        unique=False)
    op.create_index(
        op.f('ix_audit_logs_id'),
        'audit_logs',
        ['id'],
        unique=False)
    op.create_table('merchants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_table('customers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('merchant_id', sa.Integer(), nullable=False),
                    sa.Column('external_id', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_customers_external_id'),
        'customers',
        ['external_id'],
        unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(
        op.f('ix_customers_merchant_id'),
        'customers',
        ['merchant_id'],
        unique=False)
    op.create_table('merchant_policies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('merchant_id', sa.Integer(), nullable=False),
                    sa.Column('policy_version', sa.String(length=100), nullable=False),
                    sa.Column('rules_snapshot', sa.JSON(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_merchant_policies_id'),
        'merchant_policies',
        ['id'],
        unique=False)
    op.create_index(
        op.f('ix_merchant_policies_merchant_id'),
        'merchant_policies',
        ['merchant_id'],
        unique=False)
    op.create_table('payments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('currency', sa.String(length=3), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_payments_customer_id'),
        'payments',
        ['customer_id'],
        unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('failure_events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('payment_id', sa.Integer(), nullable=False),
                    sa.Column('failure_reason', sa.String(length=255), nullable=False),
                    sa.Column('context_snapshot', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_failure_events_id'),
        'failure_events',
        ['id'],
        unique=False)
    op.create_index(
        op.f('ix_failure_events_payment_id'),
        'failure_events',
        ['payment_id'],
        unique=False)
    op.create_table('payment_attempts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('payment_id', sa.Integer(), nullable=False),
                    sa.Column('attempt_time', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('error_code', sa.String(length=100), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_payment_attempts_id'),
        'payment_attempts',
        ['id'],
        unique=False)
    op.create_index(
        op.f('ix_payment_attempts_payment_id'),
        'payment_attempts',
        ['payment_id'],
        unique=False)
    op.create_table('evaluation_cases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('failure_event_id', sa.Integer(), nullable=False),
                    sa.Column('ground_truth_outcome', sa.Boolean(), nullable=False),
                    sa.Column('ground_truth_amount', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_evaluation_cases_failure_event_id'),
        'evaluation_cases',
        ['failure_event_id'],
        unique=False)
    op.create_index(
        op.f('ix_evaluation_cases_id'),
        'evaluation_cases',
        ['id'],
        unique=False)
    op.create_table('recovery_actions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('failure_event_id', sa.Integer(), nullable=False),
                    sa.Column('action_type', sa.String(length=100), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_recovery_actions_failure_event_id'),
        'recovery_actions',
        ['failure_event_id'],
        unique=False)
    op.create_index(
        op.f('ix_recovery_actions_id'),
        'recovery_actions',
        ['id'],
        unique=False)
    op.create_table('recovery_predictions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('failure_event_id', sa.Integer(), nullable=False),
                    sa.Column('model_version', sa.String(length=100), nullable=False),
                    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
                    sa.Column('recovery_probability', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_recovery_predictions_failure_event_id'),
        'recovery_predictions',
        ['failure_event_id'],
        unique=False)
    op.create_index(
        op.f('ix_recovery_predictions_id'),
        'recovery_predictions',
        ['id'],
        unique=False)
    op.create_table('evaluation_results',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('evaluation_case_id', sa.Integer(), nullable=False),
                    sa.Column('model_version', sa.String(length=100), nullable=False),
                    sa.Column('predicted_outcome', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['evaluation_case_id'], ['evaluation_cases.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_evaluation_results_evaluation_case_id'),
        'evaluation_results',
        ['evaluation_case_id'],
        unique=False)
    op.create_index(
        op.f('ix_evaluation_results_id'),
        'evaluation_results',
        ['id'],
        unique=False)
    op.create_table(
        'recovery_outcomes',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'recovery_action_id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'success',
            sa.Boolean(),
            nullable=False),
        sa.Column(
            'amount_recovered',
            sa.Float(),
            nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(
                timezone=True),
            nullable=False),
        sa.ForeignKeyConstraint(
            ['recovery_action_id'],
            ['recovery_actions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('recovery_action_id'))
    op.create_index(
        op.f('ix_recovery_outcomes_id'),
        'recovery_outcomes',
        ['id'],
        unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_recovery_outcomes_id'),
        table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index(
        op.f('ix_evaluation_results_id'),
        table_name='evaluation_results')
    op.drop_index(
        op.f('ix_evaluation_results_evaluation_case_id'),
        table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(
        op.f('ix_recovery_predictions_id'),
        table_name='recovery_predictions')
    op.drop_index(
        op.f('ix_recovery_predictions_failure_event_id'),
        table_name='recovery_predictions')
    op.drop_table('recovery_predictions')
    op.drop_index(
        op.f('ix_recovery_actions_id'),
        table_name='recovery_actions')
    op.drop_index(
        op.f('ix_recovery_actions_failure_event_id'),
        table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(
        op.f('ix_evaluation_cases_id'),
        table_name='evaluation_cases')
    op.drop_index(
        op.f('ix_evaluation_cases_failure_event_id'),
        table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    op.drop_index(
        op.f('ix_payment_attempts_payment_id'),
        table_name='payment_attempts')
    op.drop_index(
        op.f('ix_payment_attempts_id'),
        table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(
        op.f('ix_failure_events_payment_id'),
        table_name='failure_events')
    op.drop_index(op.f('ix_failure_events_id'), table_name='failure_events')
    op.drop_table('failure_events')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(
        op.f('ix_merchant_policies_merchant_id'),
        table_name='merchant_policies')
    op.drop_index(
        op.f('ix_merchant_policies_id'),
        table_name='merchant_policies')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
